In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("2  powerplant_data (1).csv")
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [3]:
# at->temp
# v->vaccum
#ap->pressure
# rh->humidity

# pe->produced energy

In [4]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
x=df.drop("PE",axis=1)
y= df["PE"]

In [6]:
x.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [7]:
y.head()

0    480.48
1    445.75
2    438.76
3    453.09
4    464.43
Name: PE, dtype: float64

In [8]:
# converting->data to tensors

In [9]:
# split data
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [11]:
df.shape

(9568, 5)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_train)

In [14]:
x_train_scaled

array([[ 0.74805289,  0.72006931, -0.32660017, -0.49711722],
       [ 0.86181948,  1.26515721, -0.98521113,  0.8181501 ],
       [ 0.93409473,  1.52314975,  0.32523844,  0.80167494],
       ...,
       [-0.22097078, -0.834965  ,  0.36756563, -0.83554456],
       [ 0.94747903,  1.14245344, -0.41971997, -0.45455637],
       [-1.77355014, -1.19049131,  1.92520594,  0.91837402]],
      shape=(7654, 4))

In [15]:
import torch
import torch.nn as nn

In [16]:
x_train_tensor = torch.tensor(x_train_scaled,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)

x_test_tensor = torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensor = torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)

In [17]:
from torch.utils.data import DataLoader,TensorDataset

In [18]:
train_dataset = TensorDataset(x_train_tensor,y_train_tensor)
test_dataset = TensorDataset(x_test_tensor,y_test_tensor)

In [19]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32)

In [20]:
# building ann model

In [26]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model = nn.Sequential(
            # 1st layer
            nn.Linear(x_train.shape[1],6),
            nn.ReLU(),

            # 2nd layer 
            nn.Linear(6,6),
            nn.ReLU(),

            # output layer
            nn.Linear(6,1)
        )

    def forward(self,x):
        return self.model(x)

In [27]:
import torch.optim as optim
model = ANN()

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

training

In [28]:
epochs = 100
train_loss = []
valid_loss = []
best_val_loss=float("inf")

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb, yb in train_loader:
        yb = yb.view(-1, 1)  # ensure shape matches model output

        optimizer.zero_grad()
        output = model(xb)
        loss = criterion(output, yb)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    epoch_train_loss = running_loss / len(train_loader)
    train_loss.append(epoch_train_loss)

    model.eval()
    running_val_loss = 0.0

    with torch.no_grad():
        for xb, yb in test_loader:
            yb = yb.view(-1, 1)
            output = model(xb)
            loss = criterion(output, yb)
            running_val_loss += loss.item()

    epoch_val_loss = running_val_loss / len(test_loader)
    valid_loss.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss:.4f} & val loss = {epoch_val_loss:.4f}")

    if epoch_val_loss<best_val_loss:
        best_val_loss= epoch_val_loss
        torch.save(model.state_dict(),"best_model.pt")

epoch 1/100 ==> train loss = 206538.8697 & val loss = 206408.8384
epoch 2/100 ==> train loss = 206347.1346 & val loss = 206191.0507
epoch 3/100 ==> train loss = 206065.4001 & val loss = 205973.4177
epoch 4/100 ==> train loss = 205868.5333 & val loss = 205755.9865
epoch 5/100 ==> train loss = 205661.0616 & val loss = 205538.6982
epoch 6/100 ==> train loss = 205441.7772 & val loss = 205321.5265
epoch 7/100 ==> train loss = 205208.7909 & val loss = 205104.5232
epoch 8/100 ==> train loss = 205057.6839 & val loss = 204887.6637
epoch 9/100 ==> train loss = 204776.2677 & val loss = 204670.8914
epoch 10/100 ==> train loss = 204563.1242 & val loss = 204454.3454
epoch 11/100 ==> train loss = 204356.1783 & val loss = 204237.8847
epoch 12/100 ==> train loss = 204127.7099 & val loss = 204021.5951
epoch 13/100 ==> train loss = 203965.3877 & val loss = 203805.3929
epoch 14/100 ==> train loss = 203714.2557 & val loss = 203589.3054
epoch 15/100 ==> train loss = 203535.7284 & val loss = 203373.3607
epoch 16/100 ==> train loss = 203284.5027 & val loss = 203157.5289
epoch 17/100 ==> train loss = 203027.4239 & val loss = 202941.8411
epoch 18/100 ==> train loss = 202831.1190 & val loss = 202726.2958
epoch 19/100 ==> train loss = 202639.2219 & val loss = 202510.8628
epoch 20/100 ==> train loss = 202375.8607 & val loss = 202295.4908
epoch 21/100 ==> train loss = 202179.9954 & val loss = 202080.2899
epoch 22/100 ==> train loss = 201974.8699 & val loss = 201865.2023
epoch 23/100 ==> train loss = 201776.3304 & val loss = 201650.2561
epoch 24/100 ==> train loss = 201537.8101 & val loss = 201435.3700
epoch 25/100 ==> train loss = 201311.3110 & val loss = 201220.6271
epoch 26/100 ==> train loss = 201106.1098 & val loss = 201005.9982
epoch 27/100 ==> train loss = 200902.7034 & val loss = 200791.4844
epoch 28/100 ==> train loss = 200686.0208 & val loss = 200577.0852
epoch 29/100 ==> train loss = 200489.6046 & val loss = 200362.8010
epoch 30/100 ==> train loss = 200249.9033 & val loss = 200148.6298
epoch 31/100 ==> train loss = 200062.0689 & val loss = 199934.6019
epoch 32/100 ==> train loss = 199811.8274 & val loss = 199720.6351
epoch 33/100 ==> train loss = 199649.7646 & val loss = 199506.8350
epoch 34/100 ==> train loss = 199431.2411 & val loss = 199293.0982
epoch 35/100 ==> train loss = 199217.8339 & val loss = 199079.5274
epoch 36/100 ==> train loss = 198952.1926 & val loss = 198866.0455
epoch 37/100 ==> train loss = 198778.0865 & val loss = 198652.7327
epoch 38/100 ==> train loss = 198572.9231 & val loss = 198439.4535
epoch 39/100 ==> train loss = 198311.3797 & val loss = 198226.3167
epoch 40/100 ==> train loss = 198164.7090 & val loss = 198013.3476
epoch 41/100 ==> train loss = 197916.7247 & val loss = 197800.4118
epoch 42/100 ==> train loss = 197683.2031 & val loss = 197587.6183
epoch 43/100 ==> train loss = 197465.8674 & val loss = 197374.9669
epoch 44/100 ==> train loss = 197276.4406 & val loss = 197162.4284
epoch 45/100 ==> train loss = 197050.8567 & val loss = 196949.9792
epoch 46/100 ==> train loss = 196856.1887 & val loss = 196737.6717
epoch 47/100 ==> train loss = 196639.9844 & val loss = 196525.4507
epoch 48/100 ==> train loss = 196439.5865 & val loss = 196313.3445
epoch 49/100 ==> train loss = 196202.2553 & val loss = 196101.3556
epoch 50/100 ==> train loss = 196003.1330 & val loss = 195889.5061
epoch 51/100 ==> train loss = 195791.5604 & val loss = 195677.7438
epoch 52/100 ==> train loss = 195584.7611 & val loss = 195466.1232
epoch 53/100 ==> train loss = 195365.1804 & val loss = 195254.6193
epoch 54/100 ==> train loss = 195155.5000 & val loss = 195043.1740
epoch 55/100 ==> train loss = 194948.4378 & val loss = 194831.8988
epoch 56/100 ==> train loss = 194727.7682 & val loss = 194620.7371
epoch 57/100 ==> train loss = 194540.5335 & val loss = 194409.6904
epoch 58/100 ==> train loss = 194274.4673 & val loss = 194198.7322
epoch 59/100 ==> train loss = 194116.3195 & val loss = 193987.9145
epoch 60/100 ==> train loss = 193881.9072 & val loss = 193777.2124
epoch 61/100 ==> train loss = 193697.2583 & val loss = 193566.5976
epoch 62/100 ==> train loss = 193474.8714 & val loss = 193356.1249
epoch 63/100 ==> train loss = 193238.6026 & val loss = 193145.7391
epoch 64/100 ==> train loss = 193015.6319 & val loss = 192935.4943
epoch 65/100 ==> train loss = 192799.2629 & val loss = 192725.3401
epoch 66/100 ==> train loss = 192625.5139 & val loss = 192515.3785
epoch 67/100 ==> train loss = 192409.4230 & val loss = 192305.4249
epoch 68/100 ==> train loss = 192244.5130 & val loss = 192095.6409
epoch 69/100 ==> train loss = 191998.9181 & val loss = 191885.9419
epoch 70/100 ==> train loss = 191751.8419 & val loss = 191676.3602
epoch 71/100 ==> train loss = 191573.6165 & val loss = 191466.9183
epoch 72/100 ==> train loss = 191367.7403 & val loss = 191257.5658
epoch 73/100 ==> train loss = 191138.8754 & val loss = 191048.3398
epoch 74/100 ==> train loss = 190980.4391 & val loss = 190839.2579
epoch 75/100 ==> train loss = 190701.2874 & val loss = 190630.2212
epoch 76/100 ==> train loss = 190559.1327 & val loss = 190421.3541
epoch 77/100 ==> train loss = 190313.2091 & val loss = 190212.6019
epoch 78/100 ==> train loss = 190122.9111 & val loss = 190003.9630
epoch 79/100 ==> train loss = 189880.9192 & val loss = 189795.4235
epoch 80/100 ==> train loss = 189692.9667 & val loss = 189587.0553
epoch 81/100 ==> train loss = 189521.8365 & val loss = 189378.7341
epoch 82/100 ==> train loss = 189278.6794 & val loss = 189170.5546
epoch 83/100 ==> train loss = 189071.8143 & val loss = 188962.4368
epoch 84/100 ==> train loss = 188861.7199 & val loss = 188754.5132
epoch 85/100 ==> train loss = 188679.8997 & val loss = 188546.6503
epoch 86/100 ==> train loss = 188466.6745 & val loss = 188338.9302
epoch 87/100 ==> train loss = 188238.3997 & val loss = 188131.2976
epoch 88/100 ==> train loss = 188018.6452 & val loss = 187923.8048
epoch 89/100 ==> train loss = 187817.2043 & val loss = 187716.4288
epoch 90/100 ==> train loss = 187621.9441 & val loss = 187509.1391
epoch 91/100 ==> train loss = 187409.6313 & val loss = 187301.9910
epoch 92/100 ==> train loss = 187176.9634 & val loss = 187094.9572
epoch 93/100 ==> train loss = 186998.1465 & val loss = 186888.0397
epoch 94/100 ==> train loss = 186812.8340 & val loss = 186681.2221
epoch 95/100 ==> train loss = 186590.4124 & val loss = 186474.5214
epoch 96/100 ==> train loss = 186362.8318 & val loss = 186267.9191
epoch 97/100 ==> train loss = 186200.5501 & val loss = 186061.5126
epoch 98/100 ==> train loss = 185949.9058 & val loss = 185855.1424
epoch 99/100 ==> train loss = 185757.7048 & val loss = 185648.9116
epoch 100/100 ==> train loss = 185573.8344 & val loss = 185442.7691

In [30]:
model.load_state_dict(torch.load("best_model.pt"))

evaluation

In [31]:
model.eval()
with torch.no_grad():
    train_pred =model(x_train_tensor)
    test_pred = model(x_test_tensor)
    train_mse_loss = criterion(train_pred,y_train_tensor)
    test_mse_loss = criterion(test_pred,y_test_tensor)
    print(train_mse_loss.item())
    print(test_mse_loss.item())

185453.71875
185453.71875

In [32]:
from sklearn.metrics import r2_score
print(r2_score(y_test,test_pred))

ValueError: Found input variables with inconsistent numbers of samples: [1914, 7654]